### ISSUE TITLE
nRF5 Command Line Tools: Win64 9.8.1が存在しません。

### ISSUE THREAD

**Issue by EbesumotoKeisuke** [cami/BG96_controller_for_nRF52840_LibforArduino#18]
2019年7月1日にArduino IDE version windows Store 1.8.21.0をインストールしたところ、
APPDATA%/Local/Arduino15/
というフォルダは存在せず、代わりに
~Documents\ArduinoData\packages\adafruit\hardware\nrf52
というところにnrf52が存在しています。
これは同じものととらえて大丈夫でしょうか？

**Comment by NaotoFujihiro** [comment]
Issueありがとうございます。
Windows StoreでインストールできるArduinoIDEは、動作保証対象外です。
